/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cn.org.tpeach.nosql.view;

import java.awt.Color;
import java.awt.Dimension;

import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.border.Border;

import cn.org.tpeach.nosql.constant.PublicConstant;

/**
 *
 * @author smart
 */
public class HomeTabbedPanel extends javax.swing.JPanel {

	private static final long serialVersionUID = -5054008338538674819L;

	/**
	 * Creates new form HomeTabbedPanel
	 */
	public HomeTabbedPanel() {
		initComponents();
		jLabel1.setText("<html><div style='font-family:\"宋体\";color:#999999;min-width:100px;font-size:14px;margin:0,10px,0,10px;'>Redis is an open source (BSD licensed), in-memory data structure store, used as a database, cache and message broker. It supports data structures such as strings, hashes, lists, sets, sorted sets with range queries, bitmaps, hyperloglogs, geospatial indexes with radius queries and streams. Redis has built-in replication, Lua scripting, LRU eviction, transactions and different levels of on-disk persistence, and provides high availability via Redis Sentinel and automatic partitioning with Redis Cluster"
				+ "</div></html>");
		jLabel1.setBorder(BorderFactory.createEmptyBorder(0, 10, 0, 10));
		jLabel1.setBackground(Color.RED);
		jLabel2.setIcon(PublicConstant.Image.logo);
		jLabel2.setBorder(BorderFactory.createEmptyBorder(0, 30, 0, 10));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new Dimension(RedisMainWindow.contentPane.getWidth()-RedisMainWindow.treePanel.getWidth(),RedisMainWindow.contentPane.getWidth()));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("45");
        add(jLabel1, java.awt.BorderLayout.CENTER);
        add(jLabel2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
